source 'https://rubygems.org'

gem 'rails', '3.2.13'
gem 'foreman'
gem 'sqlite3'
gem 'cityhash', '= 0.6.0'
gem 'cacheable', require: "cacheable", git: "git://github.com/Shopify/cacheable.git"
gem 'memcache-client'
gem 'unicorn'
gem 'debugger'

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

